version: '2.2'
services:
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
  node:
    image: peliculasbe
    ports:
      - "4000:4000"    
    links:
      - mongo
      - redis
    depends_on:
      - mongo
  redis:
    image: redis
    ports:
      - "6379:6379"